#webpage address

url: "https://kaushalgianchandani.github.io/"

baseurl:

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#HTML head
author: "Kaushal Gianchandani"
lang: "en"
title: "Kaushal Gianchandani"
