#webpage address

url: "https://kaushalgianchandani.github.io/"

baseurl:

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#HTML head
author: "Kaushal Gianchandani"
lang: "en"
title: "Kaushal Gianchandani"

description: "Webpage of Kaushal Gianchandani"
keywords: "kaushal gianchandani, niser, nonlinear dynamics, geophysical fluid dynamics"

background-img: "../img/backgroud.png"
me-img: "/img/KaushalGianchandani.png"

#dynamic text for header
dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	4 # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:	# You can add HTML Tags in the Text
  - text: "Aspiring physicist"
  - text: "Signal Processing"
  - text: "Nonlinear dynamics"
  - text: "Geophysical fluid dynamics"

#For the Blog
post-preview-words: 80

jekyll-paginate: 5

fb-share: True
twitter-share: True
google-plus-share: True
linkedin-share: True
disqus-shortname: "kaushal.g"

#timeline
events:
  - image: "/img/career/Cesar_NASA.jpg"
    date: "2016"
    description: "NASA Earth and Space Science Graduate Fellow"
  - image: "/img/career/Cesar_GFD.png"
    date: "Summer 2015"
    description: "Fellow of the Geophysical Fluid Dynamics Program"
  - image: "/img/career/Cesar_Pier.jpg"
    date: "September 2013"
    description: "Joined the Climate-Ocean-Atmosphere Program at Scripps, UC San Diego"
  - image: "/img/career/ms.png"
    date: "July 2013"
    description: "Graduated with a MSc degree from University of Sao Paulo"
  - image: "/img/career/formandos.png"
    date: "February 2011"
    description: "Graduated with a BSc degree from University of Sao Paulo"

# First image of the Career timeline
career-img: "/img/career/Cesar_Freshman.png"
