#webpage address
url: "https://kaushalgianchandani.github.io/"
baseurl: ""

# Forces https everywhere in your website, except when you serve it locally
force-https: True

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Supervisors: 'supervisors'
  Literature: 'literature'
  Blog: 'latest-post'
  Contact: 'contact'

# web-app-mode: True

#HTML head
author: "Kaushal Gianchandani"
lang: "en"
title: "Kaushal Gianchandani"
favicon: "/img/niser.png"
description: "Webpage of Kaushal Gianchandani"
keywords: "kaushal gianchandani, niser, nonlinear dynamics, geophysical fluid dynamics"

background-img: "../img/background.png"
me-img: "/img/KaushalGianchandani.png"

color-browser: "#000000"
apple-status-bar-style: "black"

#dynamic text for header
dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	4 # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:	# You can add HTML Tags in the Text
  - text: "Aspiring physicist"
  - text: "Physical oceanography"
  - text: "Geophysical fluid dynamics"
  - text: "Signal Processing"
  - text: "Nonlinear dynamics"


#blog
enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "kaushal.g"


#timeline

events:
  - image: "/img/timeline/ens_lyon.png"
    date: "May - July 2016"
    description: "Summer Intern at Laboratoire de Physique of École normale supérieure de Lyon"
  - image: "/img/timeline/wapp.png"
    date: "December 2015"
    description: "Participant at the 10th Winter School on Astropartical Physics at Bose Institute - Darjeeling"
  - image: "/img/timeline/imsc.png"
    date: "June - July 2015"
    description: "Summer Research Fellow in Theoretical Physics at Institute of Mathematical Sciences (IMSc) - Chennai"
  - image: "/img/timeline/iiserk.png"
    date: "May - June 2014"
    description: "Summer Intern at Indian Institute of Science Education and Research - Kolkata"

# First image of the timeline
timeline-img: "/img/timeline/begin.png"

#contact layout
email: "kaushal.g@niser.ac.in"

#social
social:
  - title: "facebook"
    url: "https://www.facebook.com/kaushal.gianchandani"
  - title: "twitter"
    url: "https://twitter.com/kgian24"
  - title: "github"
    url: "https://github.com/kaushalgianchandani"

#404 page
404-img: "/img/labtocat.jpg"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems:
  - jekyll-paginate
  - jemoji
