#webpage address

url: "https://kaushalgianchandani.github.io/"

baseurl:

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#HTML head
author: "Kaushal Gianchandani"
lang: "en"
title: "Kaushal Gianchandani"

description: "Webpage of Kaushal Gianchandani"
keywords: "kaushal gianchandani, niser, nonlinear dynamics, geophysical fluid dynamics"

background-img: "../img/backgroud.png"
me-img: "/img/KaushalGianchandani.png"

#dynamic text for header
dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	4 # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:	# You can add HTML Tags in the Text
  - text: "Aspiring physicist"
  - text: "Signal Processing"
  - text: "Nonlinear dynamics"
  - text: "Geophysical fluid dynamics"

#For the Blog
post-preview-words: 80

jekyll-paginate: 5

fb-share: True
twitter-share: True
google-plus-share: True
linkedin-share: True
disqus-shortname: "kaushal.g"

#timeline
events:
  - image: "/img/timeline/ens_lyon"
    date: "2016"
    description: "NASA Earth and Space Science Graduate Fellow"

# First image of the Career timeline
career-img: "/img/career/Cesar_Freshman.png"

#Contact layout
email: "kaushal.g@niser.ac.in"

#social media
  - title: "facebook"
    url: "https://www.facebook.com/kaushal.gianchandani"
  - title: "twitter"
    url: "https://twitter.com/kgian24"
  - title: "github"
    url: "https://github.com/kaushalgianchandani"

# don't alter a lot
pages_list:
  About: 'about'
  Timeline: 'timeline'
  Code: 'code'
  Supervisors: 'supervisors'
  Contact: 'contact'
#  Publications: 'publications'


# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
